### ISSUE TITLE
[Bug] Some pages don't unhide all entries

### ISSUE THREAD

**Issue by Wulfson** [tariel36/MAL-Unretard-Related-Entries#1]
Using Greasemonkey in Firefox, the script has a minor issue on particularly large lists, like the one found on the [One Piece](https://myanimelist.net/anime/21/One_Piece) page.

![one_piece](https://github.com/tariel36/MAL-Unretard-Related-Entries/assets/4459854/7b9334b6-6e5f-47be-8045-060c4149f298)

I was able to fix it by changing the Unfold code here:
https://github.com/tariel36/MAL-Unretard-Related-Entries/blob/935f2646a6547340542b92effd08538482e9d889/MAL-Unretard-Related-Entries.user.js#L32-L34

to this:
```javascript
  Array.from(document.getElementsByClassName("hide-entry")).forEach(function (el) {
    el.removeAttribute("style");
    el.classList.remove("hide-entry");
  });
```
I don't know if that has any other side-effects.

**Comment by tariel36** [comment]
Thanks, I will have a loot at that within a week, as currently I'm a little busy with IRL matters.

**Comment by tariel36** [comment]
@Wulfson In my Firefox (totally clean install) it worked without issues with old code for One Piece, but applied your fix anyway. Check if it works for you now (it should be version 1.0.2 or above).

**Comment by Wulfson** [comment]
It's actually broken entirely for me on 1.0.3...sticking these lines:
https://github.com/tariel36/MAL-Unretard-Related-Entries/blob/master/MAL-Unretard-Related-Entries.user.js#L19-L22
into 1.0.1 works as expected, though

**Comment by tariel36** [comment]
Can you provide error message if it exists?

Are you still testing on the One Piece link?

Do you have any other script or extension that may influence MAL source html? If so, please test on clean browser.

**Comment by tariel36** [comment]
Closed for inactivity / not reproducible.
